### ISSUE TITLE
Missing environment string, ERROR: The \"DISPLAY\" variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by cw1704** [ROS-2-Dev/turtlebot3_docker#11]
The following 2 error shows up after calling `docker compose build`

ERROR: The \"DISPLAY\" variable is not set. Defaulting to a blank string.
ERROR: The \"HOME\" variable is not set. Defaulting to a blank string.

**Comment by ambrosekwok** [comment]
I have not found mentioned issues.

We may got different $DISPLAY and $HOME, fixed values may let others unable to run.

These environment variables should exist by default in Linux. What is the host OS you use?

**Comment by JosefGst** [comment]
I tested Wings suggested changes and it didn't break my docker so I'll add it.

**Comment by ambrosekwok** [comment]
I checked in ubuntu 20.04 and ubuntu 22.04, both worked with default display manager.
Seems the $HOME env variable only required when I switched to different one.
